services:
  app:
    image: php:7.1-fpm
    container_name: laravel_app
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      laravel:
        ipv4_address: 192.168.1.100
    depends_on:
      - mongodb
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile

  webserver:
    image: nginx:alpine
    container_name: laravel_webserver
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8000:80"
    networks:
      laravel:
        ipv4_address: 192.168.1.101
    depends_on:
      - app

  mongodb:
    image: mongo:4.4
    container_name: laravel_mongodb
    ports:
      - "27017:27017"
    networks:
      laravel:
        ipv4_address: 192.168.1.102
    volumes:
    - mongodbdata:/data/db
    - ./docker/mongodb/init:/docker-entrypoint-initdb.d 
    command: ["mongod", "--bind_ip", "0.0.0.0"]

networks:
  laravel:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24

volumes:
  mongodbdata: